name: CompleteTest
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  rust-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Rust backend
      run: cargo build --verbose
    - name: Run Rust tests
      run: cargo test --verbose

  node-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: List directory structure
      run: dir /s /b
    - name: Install dependencies
      run: |
        cd cbzserver/frontend
        npm ci
    - name: Build frontend
      run: |
        cd cbzserver/frontend
        npm run build
    - name: Run frontend tests
      run: |
        cd cbzserver/frontend
        npm test

